config/routes.rb
Rails.application.routes.draw do
  resources :squawks
  devise_for :users

  root 'squawks#index'

  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/squawk.rb
class Squawk < ActiveRecord::Base
  belongs_to :user

  validates :title, presence: true, length: { maximum: 140 }
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :squawks
  devise :database_authenticatable, :registerable, :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/squawks_controller.rb
class SquawksController < ApplicationController

  def index
    @squawks = Squawk.all.order("created_at DESC")
  end

  def show
    @squawk = Squawk.find_by_id(params[:id])
  end

  def new
    @squawk = Squawk.new
  end

  def edit
    @squawk = Squawk.find_by_id(params[:id])
  end

  def create
    @squawk = current_user.squawks.build(squawk_params)


    respond_to do |format|
      if @squawk.save
        format.html { redirect_to @squawk, notice: 'Squawk was successfully created.' }
        format.json { render :show, status: :created, location: @squawk }
      else
        format.html { render :new }
        format.json { render json: @squawk.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @squawk = Squawk.find_by_id(params[:id])
    respond_to do |format|
      if @squawk.update(squawk_params)
        format.html { redirect_to @squawk, notice: 'Squawk was successfully updated.' }
        format.json { render :show, status: :ok, location: @squawk }
      else
        format.html { render :edit }
        format.json { render json: @squawk.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @squawk = Squawk.find(params[:id])
    @squawk.destroy
    respond_to do |format|
      format.html { redirect_to squawks_url, notice: 'Squawk was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_squawk
      @squawk = Squawk.find(params[:id])
    end

    def squawk_params
      params.require(:squawk).permit(:name, :title, :content)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/squawk_helper.rb
module SquawkHelper
end

app/helpers/squawks_helper.rb
module SquawksHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li><a href="<%= squawks_path %>"><i class="fa fa-2x fa-home"></i> Home</a></li>
          </ul>
          <a class="navbar-brand" href="/"><%= image_tag 'pigeon-square.png', class: 'logo' %></a>
          <ul class="pull-right nav navbar-nav">
            <li>
              <input class="search-input" type="text" placeholder="Search Pigeon">
            </li>
            <li class="btn btn-theme">
              <% if user_signed_in? %>
              <li>
                <div class="dropdown">
                    <a class="dropdown-toggle" type="button" id="dropdownMenu1" data-toggle="dropdown" aria-haspopup="true" aria-expanded="true">
                        <%= image_tag 'thumbnail.jpg', class: 'thumbnail' %>
                    </a>
                <ul class="dropdown-menu" aria-labelledby="dropdownMenu1">
                  <li>
                    <%= link_to('Edit Profile', edit_user_registration_path) %>
                  </li>
                  <li>
                  <%= link_to('My squawks', squawks_path(mine: true)) %>
                  </li>
                  <li>
                    <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
                  </li>
                </ul>
                </div>
              </li>
              <li class="mobilelogout">
                    <%= link_to('Edit Profile', edit_user_registration_path) %>
                  </li>
              <li class="mobilelogout">
                <%= link_to('My squawks', squawks_path(mine: true)) %>
              </li>
              <li class="mobilelogout">
                    <%= link_to('Logout', destroy_user_session_path, :method => :delete) %>
              </li>
              <% else %>
            <li>
              <%= link_to('Sign Up', new_user_registration_path)  %>
            </li>
            <li>
              <%= link_to('Login', new_user_session_path)  %>
            </li>
              <% end %>
            </li>
            <li><a href="<%= new_squawk_path %>"><button type="button" class="btn btn-success"><i class="fa fa-exclamation"></i> Squawk</button></a></li>


        </ul>
        </div>
        </div><!--/.nav-collapse -->
      </div>
    </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pigeon</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'pigeon-square.png' %>
</head>
<body>
<%= render partial: 'layouts/header.html.erb' %>
<% if notice %>
      <p class="alerttop alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alerttop alert alert-danger"><%= alert %></p>
    <% end %>
<%= yield %>

</body>
</html>

app/views/squawks/_form.html.erb
<%= form_for(@squawk) do |f| %>
  <div class="field">
    <%= f.label :squawk %><br>
    <%= f.text_field :title %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/squawks/_others.html.erb
<div class="col-xs-12 col-sm-3 others">
Other tweets
</div>

app/views/squawks/_profile.html.erb
<div class="col-xs-12 col-sm-3 others">
    <div class="twPc-div">
        <a class="twPc-bg twPc-block"></a>

      <div>
        <a title="Mert Salih Kaplan" href="https://twitter.com/dylanjhunt" class="twPc-avatarLink">
          <%= image_tag 'profile.jpg', class: 'profile' %>
        </a>

        <div class="twPc-divUser">
          <div class="twPc-divName">
            <a href="https://twitter.com/dylanjhunt">Dylan Hunt</a>
          </div>
          <span>
            <a href="https://twitter.com/dylanjhunt">@<span>dylanjhunt</span></a>
          </span>
        </div>

        <div class="twPc-divStats">
          <ul class="twPc-Arrange">
            <li class="twPc-ArrangeSizeFit">
              <a href="https://twitter.com/dylanjhunt" title="9.840 Tweet">
                <span class="twPc-StatLabel twPc-block">Squawks</span>
                <span class="twPc-StatValue"><%= @squawks.count %></span>
              </a>
            </li>
            <!--<li class="twPc-ArrangeSizeFit">
              <a href="https://twitter.com/dylanjhunt/following" title="885 Following">
                <span class="twPc-StatLabel twPc-block">Following</span>
                <span class="twPc-StatValue">885</span>
              </a>
            </li>
            <li class="twPc-ArrangeSizeFit">
              <a href="https://twitter.com/dylanjhunt/followers" title="1.810 Followers">
                <span class="twPc-StatLabel twPc-block">Followers</span>
                <span class="twPc-StatValue">1,810</span>
              </a>
            </li>-->
          </ul>
        </div>
      </div>
    </div>
</div>

app/views/squawks/edit.html.erb
<div class="container">
  <div class="login-container col-xs-12 col-sm-8 col-md-6 col-md-offset-3">
    <div id="output"></div>
    <div class="form-box">
      <%= image_tag "pigeon-square.png" %>

<h1>Editing Squawk</h1>

<%= render 'form' %>

<%= link_to 'Show', @squawk %> |

</div>
</div>
</div>

app/views/squawks/index.html.erb
<div class="col-xs-12">
<div class="desktoppartial">
<%= render partial: 'squawks/profile.html.erb' %>
</div>
<div class="col-xs-12 col-sm-6 squawks">
    <% @squawks.each do |squawk| %>
    <div class="squawk">
      <div class="userinfo">
    <%= image_tag 'thumbnail.jpg', class: 'thumbnail' %>
      </div>
        <h2><%= squawk.title %></h2>
        <p><%= squawk.created_at %></p>
        <div class="pull-right">
        <a href="<%= edit_squawk_path(squawk) %>"><i class="fa fa-pencil-square-o"></i> |
        <%= link_to 'Delete', squawk, method: :delete, data: { confirm: 'Are you sure?' } %>
      </div>
      </div>
    <% end %>
<br>
</div>

</div>

app/views/squawks/new.html.erb
<div class="container">
  <div class="login-container col-xs-12 col-sm-8 col-md-6 col-md-offset-3">
    <div id="output"></div>
    <div class="form-box">
      <%= image_tag "pigeon-square.png" %>
      <h2>Squawk!!!</h2>

<%= render 'form' %>
</div>
  </div>
</div>

app/views/squawks/show.html.erb
<div class="container">
  <div class="login-container col-xs-12 col-sm-8 col-md-6 col-md-offset-3">
    <div id="output"></div>
    <div class="form-box">
      <%= image_tag "pigeon-square.png" %>

<h2>
  <%= @squawk.title %>
</h2>
<%= @squawk.user.username %>

<%= link_to 'Edit', edit_squawk_path(@squawk) %> |
</div>
</div>
</div>